spring:
  profiles:
    active: dev
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sarafan
    username: u
    password: p
  jooq:
    sql-dialect: postgres

server:
  port: 8080

logging:
  level:
    web: info
